site_name: 史建威个人博客 | 11时序矩阵本体论
site_url: https://sjw719.github.io/11/
repo_url: https://github.com/sjw719/11
edit_uri: blob/main/docs/
site_author: 史建威
site_description: 山东威海 · 理论物理EPD工程组官方文档站
copyright: Copyright © 2026 史建威 · 山东威海理论物理EPD工程组
remote_branch: gh-pages

theme:
  name: material
  language: zh
  features:
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.action.view
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: 切换至暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-night
        name: 切换至亮色模式

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sjw719
      name: GitHub 主页
    - icon: fontawesome/solid/envelope
      link: mailto:1625027134@qq.com
      name: 联系邮箱
  generator: false

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  - js/katex.js

plugins:
  - search
  - glightbox:
      width: 80%
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
